name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/marble-backend:latest .

      - name: Push
        run: |
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "marble-backend"
          image: "eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest"
          env_vars: |
            PG_HOSTNAME=/cloudsql/${{ secrets.GCP_PROJECT_ID }}:europe-west9:marble-sandbox
            PG_USER=postgres
            GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
          secrets: |
            PG_PASSWORD=POSTGRES_SANDBOX:latest
          region: "europe-west9"
          flags: "--port=8080 --service-account=marble-backend-cloud-run@tokyo-country-381508.iam.gserviceaccount.com --add-cloudsql-instances=tokyo-country-381508:europe-west9:marble-sandbox"
